.TH parallel 1 "Version 1.3.1" "User Commands"
.SH NAME
parallel, ssh_parallel \- execute lines of input in parallel

.SH SYNOPSIS
.B parallel 
processes

.B ssh_parallel
[-h] [-s TIME] [-n NICE] [-v] directory machine1 processes1 [machine2 processes2 [...]]
.SH DESCRIPTION
.B parallel
and 
.B ssh_parallel
run lines passed in on the standard input in a 
.B BASH(1) 
shell, in parallel.
.B parallel 
runs the commands on the local machine, and ssh_parallel runs the commands
using SSH on any number of machines. Passwordless SSH must be set up for the
.B ssh_parallel 
to operate. The program terminates when the final child process terminates.

.SH PARALLEL 
Command line arguments:
.TP
\fBprocesses\fR
number of processes to run in parallel

.P
In the event of
.B fork(2)
failing, parallel will not loose the line: it will keep retrying.


.SH SSH_PARALLEL
Command line arguments:
.TP
.B -h
print a help message
.TP
.B -s TIME
set sleep timeout to TIME seconds
.TP
.B -n NICE
run processes with priority NICE
.TP
.B -v
verbose operation
.TP
.B directory
directory to operate in. \fB.\fR refers to the current working directory. This 
may not be the same text as $PWD, since some shells keep track of followed symlinks. 
The most suitable choice depends on your environment.


.TP
.B machine1 processes1
Machine to execute processes on, and number of processes to execute in parallel. 
.B machine
can be given in 
.B user@host
format. A machine name of
.B """"""
corresponds to the local machine. SSH is not used in this case. 

.TP 
.B machine2 processes2 ...
Additional machine to run processes on.

.P

There are several retryable errors which can occur. If 
.B ssh(1),
process spawning,
or the change to the working directory on the remote machine
fails, then the line will be saved and re-executed. These conditions
are indicated by the return codes 255, 254 and 253 respectively. Since
.B ssh(1)
returns the return code of the remote executing script, if the remote script
returns any of these error codes, it will be rerun, and the corresponding
error reported.

A failure of 
.B ssh(1)
or 
.B cd
can indicate an intermittent network problem. As a result, the machine which failed
is put to sleep for TIME seconds (default 10). Each available process on a machine 
counts as a different machine.

.SH EXAMPLES
.TP
Convert all PNG files to JPEG files using 4 simultaneous processes:
 ls | grep \(aq\e.png$\(aq | sed -e \(aqs/\(.*\)png/convert & \e1jpg/\(aq | parallel 4
.TP
Perform the same operation on bigserver and hugeserver, using more processes:
 ls | grep \(aq\e.png$\(aq | sed -e \(aqs/\(.*\)png/convert & \e1jpg/\(aq | ssh_parallel $PWD bigserver 8 hugeserver 16


.SH AUTHOR
Edward Rosten

.SH COPYRIGHT
Copyright \(co 2007, 2008 Edward Rosten.
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.sh SEE ALSO
.B bash(1)
.B ssh(1)
.B renice(1)

.pm
.pm
sdad
